[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#050505"
foreground = "#DCD7BA"

[colors.normal]
black = "#080808"
red = "#C34043"
green = "#76946A"
yellow = "#C0A36E"
blue = "#7E9CD8"
magenta = "#957FB8"
cyan = "#6A9589"
white = "#C8C093"

[colors.bright]
black = "#0e0e0e"
red = "#E82424"
green = "#98BB6C"
yellow = "#E6C384"
blue = "#7FB4CA"
magenta = "#938AA9"
cyan = "#7AA89F"
white = "#E6E2CA"
